# Generated by Django 3.0.7 on 2020-07-05 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='receiver',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rater',
            new_name='requester',
        ),
    ]
