# Generated by Django 3.0.7 on 2020-06-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200614_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
