# Generated by Django 3.0.7 on 2020-07-05 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200705_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_rate', to=settings.AUTH_USER_MODEL, verbose_name='receiver'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_rate', to=settings.AUTH_USER_MODEL, verbose_name='rater'),
        ),
    ]
