FORMAT: 1A
HOST: https://vrmates.kg/

# Vrmates

## Users Collection [/users/]

### List All Users [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "first_name": "Random",
                "last_name": "User",
                "username": "Admin",
                "email": "kingdoom_98@mail.ru",
                "birthday": "1998-12-12",
                "age": 22,
                "gender": "Male",
                "phone": "9965591295572",
                "address": "Address",
                "zip_code": "720010",
                "country": "KGZ",
                "city": "Bishkek",
                "state": "State",
                "points": 0,
                "rating_count": 0,
                "avg_rating": 0,
                "avg_rating_last_ten": 0,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiZXhwIjoxNTk3NjcyMTE1fQ.Vg1P1_3J6F2ghttoMPMxbBWFquqHM_M8qPV_X7SjAu0"
            }
        ]

## User's Registration [/users/registration/]

### Register a New User [POST]

+ Request (application/json)

        {
            "first_name": "Alex",
            "last_name": "Chirkov",
            "username": "Scareface",
            "email": "aleksei.chirkov.98@gmail.com",
            "birthday": "2020-12-24",
            "gender": [
                "Male",
                "Female",
                "Others",
            ],
            "phone": "996559129557",
            "address": "Moscow st. 219",
            "zip_code": 720010,
            "country": "Kyrgyzstan",
            "city": "Bishkek",
            "state": "Chui",
            "password": "MyPassword1",
            "password2": "MyPassword1"
        }

+ Response 201 (application/json)

    + Headers

            Location: /users/registration/

    + Body

            {
                "response": "Successfully created a new user. Please check your email and verify your account.",
                "email": "aleksei.chirkov.98@gmail.com",
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiZXhwIjoxNTk3NjcyMTE1fQ.Vg1P1_3J6F2ghttoMPMxbBWFquqHM_M8qPV_X7SjAu0"
            }

## User's Login [/users/login/]

### Login User [POST]

+ Request (application/json)

        {
            "email": "aleksei.chirkov.98@mail.ru",
            "password": "MyPassword1"
        }

+ Response 201 (application/json)

    + Headers

            Location: /users/registration/

    + Body

            {
                "email": "tektonik_boy98@mail.ru",
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTk3NjczNjI0fQ.WlkOhSg4z7FWKWNHB5dpkiSXm2flXBYD3XeR0ZRL8tY"
            }

## Rating [/users/rating/]

### Rating List [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "requester": {
                "first_name": "Alex",
                "last_name": "Chirkov",
                "username": "Scareface",
                "email": "tektonik_boy98@mail.ru",
                "birthday": "2020-06-18",
                "age": 0,
                "gender": "Male",
                "phone": "996559129557",
                "address": "Moscow st.",
                "zip_code": "720010",
                "country": "KGZ",
                "city": "Bishkek",
                "state": "Chui",
                "points": 80,
                "rating_count": 0,
                "avg_rating": 0,
                "avg_rating_last_ten": 0,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTk3NzY5NjQwfQ.X6pXU5lWy_ZKdqJcQtAjey4d72dTNZbtP__nRKRPE9Y"
            },
            "provider": {
                "first_name": "Random",
                "last_name": "User",
                "username": "Admin",
                "email": "kingdoom_98@mail.ru",
                "birthday": "1998-12-12",
                "age": 22,
                "gender": "Male",
                "phone": "9965591295572",
                "address": "Address",
                "zip_code": "720010",
                "country": "KGZ",
                "city": "Bishkek",
                "state": "State",
                "points": 0,
                "rating_count": 1,
                "avg_rating": 2.0,
                "avg_rating_last_ten": 2.0,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiZXhwIjoxNTk3NzY5NjQwfQ.-sxOcXs0_UR_5-wG9YJqEi4VrEUnZzckaUeJMNUBvDY"
            },
            "rating": 2.0,
            "text": "good",
            "date": "2020-06-19"
        }

### Rate User [POST]

+ Request (application/json)

        {
            "requester": 1,
            "provider": 1,
            "rating": 2.4,
            "text": "User's review",
            "date": "2020-11-21"
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/service/

    + Body

            {
                "id": 2,
                "rating": 2.4,
                "text": "User's review",
                "date": "2020-06-19",
                "requester": 1,
                "provider": 1
            }

## Delivery [/api/delivery/]

### Delivery List [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "requester": {
                "first_name": "",
                "last_name": "",
                "username": "Admin",
                "email": "tektonik_boy98@mail.ru",
                "birthday": null,
                "age": 0,
                "gender": "",
                "phone": null,
                "address": null,
                "zip_code": null,
                "country": null,
                "city": null,
                "state": null,
                "points": 0,
                "rating_count": 0,
                "avg_rating": 0,
                "avg_rating_last_ten": 0,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAxOTAxMDc1fQ.SzpfdA02loxg2Xe6y1F0rRtInPXfzFttiZtalLCljnY"
            },
            "provider": null,
            "pickup_location": "das",
            "drop_off_location": "asdasdas",
            "deadline": "2020-08-06",
            "status": "Created, not accepted",
            "title": "Title",
            "text": "asasssdf",
            "created": "2020-08-06",
            "is_checked": true
        }

### Create Delivery [POST]

+ Request (application/json)

        {
            "requester": 1, <!-- Id -->
            "provider": 1, <!-- Id -->
            "service_type": [ 
                "Package delivery",
                "Airport pick up/drop off"
            ],
            "start_location": "Start",
            "end_location": "End",
            "deadline": "2020-06-18T12:07:46Z",
            "status": [                  <!-- By default Created, not accepted-->
                "Created, not accepted",
                "Accepted/in process",
                "Successfully done",
                "Not confirmed",
                "Canceled"
            ],
            "title": "Title",
            "text": "Text",
            "is_checked": False <!-- Needs to admin validation, user must not have this field when he posts -->
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/service/

    + Body

            {
                "id": 2,
                "service_type": "Package delivery",
                "start_location": "Start",
                "end_location": "End",
                "deadline": "2020-06-18T12:07:46Z",
                "status": "Created, not accepted",
                "title": "Title",
                "text": "Text",
                "is_checked": false,
                "requester": 1,
                "provider": 1
            }

## Pick Up [/api/pickup/]

### Pick Up List [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "requester": {
                "first_name": "",
                "last_name": "",
                "username": "Admin",
                "email": "tektonik_boy98@mail.ru",
                "birthday": null,
                "age": 0,
                "gender": "",
                "phone": null,
                "address": null,
                "zip_code": null,
                "country": null,
                "city": null,
                "state": null,
                "points": 0,
                "rating_count": 0,
                "avg_rating": 0,
                "avg_rating_last_ten": 0,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAxOTAxMDc1fQ.SzpfdA02loxg2Xe6y1F0rRtInPXfzFttiZtalLCljnY"
            },
            "provider": null,
            "pickup_location": "das",
            "drop_off_location": "asdasdas",
            "deadline": "2020-08-06",
            "status": "Created, not accepted",
            "title": "Title",
            "text": "asasssdf",
            "created": "2020-08-06",
            "is_checked": true
        }

### Create Pick Up [POST]

+ Request (application/json)

        {
            "requester": 1, <!-- Id -->
            "provider": 1, <!-- Id -->
            "service_type": [ 
                "Package delivery",
                "Airport pick up/drop off"
            ],
            "start_location": "Start",
            "end_location": "End",
            "deadline": "2020-06-18T12:07:46Z",
            "status": [                  <!-- By default Created, not accepted-->
                "Created, not accepted",
                "Accepted/in process",
                "Successfully done",
                "Not confirmed",
                "Canceled"
            ],
            "title": "Title",
            "text": "Text",
            "is_checked": False <!-- Needs to admin validation, user must not have this field when he posts -->
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/service/

    + Body

            {
                "id": 2,
                "service_type": "Package delivery",
                "start_location": "Start",
                "end_location": "End",
                "deadline": "2020-06-18T12:07:46Z",
                "status": "Created, not accepted",
                "title": "Title",
                "text": "Text",
                "is_checked": false,
                "requester": 1,
                "provider": 1
            }

## Hosting [/api/hosting/]

### Hosting List [GET]

+ Response 200 (application/json)

        {
            "id": 2,
            "requester": {
                "first_name": "Random",
                "last_name": "User",
                "username": "TestUser",
                "email": "admin1@mail.ru",
                "birthday": "1212-12-12",
                "age": 808,
                "gender": "Male",
                "phone": "996559129557123",
                "address": "Address",
                "zip_code": "720010",
                "country": "KGZ",
                "city": "Bishkek",
                "state": "State",
                "points": 0,
                "rating_count": 0,
                "avg_rating": 0,
                "avg_rating_last_ten": 0,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MywiZXhwIjoxNTk3NjgwNDQ4fQ.xr3D3rSaW6GzgTRwbskFJbYnaJRbN3bnfjYDXu5rw0w"
            },
            "provider": null,
            "date": "2020-06-18",
            "service_type": "Hosting",
            "title": "Title",
            "text": "Text",
            "preferences": "Private bedroom",
            "status": "Created, not accepted",
            "is_checked": true
        }

### Create Service [POST]

+ Request (application/json)

        {
            "requester": 1, <!-- Id -->
            "provider": 1, <!-- Id -->
            "date": "2020-11-21",
            "service_type": "Hosting",
            "title": "Title",
            "text": "Text",
            "preferences": [
                "Private bedroom",
                "Living room",
                "Common space"
            ],
            "status": [                  <!-- By default Created, not accepted-->
                "Created, not accepted",
                "Accepted/in process",
                "Successfully done",
                "Not confirmed",
                "Canceled"
            ],
            "is_checked": False <!-- Needs to admin validation, user must not have this field when he posts -->
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/hosting/

    + Body

            {
                "id": 5,
                "date": "2020-11-21",
                "service_type": "Hosting",
                "title": "Title",
                "text": "Text",
                "preferences": "Private bedroom",
                "status": "Created, not accepted",
                "is_checked": false,
                "requester": 1,
                "provider": 1
            }

## Services' Images [/api/delivery-images/]

### Get Image from Service [GET]

+ Response 200 (application/json)
        
        <!--/api/delivery-images/,-->
        <!--/api/pickup-images/,-->
        <!--/api/hosting-images/-->
        {
            "id": 1,
            "image": "http://localhost:8000/media/deliveries/telegram.png",
            "post": 1
        }

### Add Image to Delivery [POST]

+ Request (application/json)

        {
            "image": "http://localhost:8000/media/deliveries/telegram.png",
            "post": 1
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/hosting/

    + Body

            {
                "id": 1,
                "image": "http://localhost:8000/media/deliveries/telegram.png",
                "post": 1
            }

## Support [/api/support/]

### Support List [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "email": "admin@mail.ru",
            "title": "Title",
            "text": "text",
            "date": "2020-07-31"
        }

### Create Support [POST]

+ Request (application/json)

        {
            "email": "admin@mail.ru",
            "title": "Title",
            "text": "text"
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/support/

    + Body

            {
                "id": 1,
                "name": "Alex",
                "email": "admin@mail.ru",
                "title": "Title",
                "text": "text",
                "date": "2020-07-31"
            }

## Pick Up List Filter [/api/pickup-filters/?service_type=Package+delivery&status=Created%2C+not+accepted&created=2020-07-21]

### Pick Up List Filter [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "requester": {
                "first_name": "Aleksei",
                "last_name": "Support",
                "username": "Alex",
                "email": "kingdoom_98@mail.ru",
                "birthday": "2020-07-21",
                "age": 0,
                "gender": "Male",
                "phone": "0559129557",
                "address": "Address",
                "zip_code": "720010",
                "country": "Kyrgyzstan",
                "city": "Бишкек",
                "state": "Chui",
                "points": 20,
                "rating_count": 0,
                "avg_rating": 0,
                "avg_rating_last_ten": 0,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiZXhwIjoxNjAwNjcxNjg2fQ.Hrv_sRWj2R8Vg0C8NsCjo1YesWITZQC_gL79Ju4NVS4"
            },
            "provider": null,
            "service_type": "Package delivery",
            "start_location": "Start",
            "end_location": "End",
            "deadline": "2020-07-21T12:21:46Z",
            "status": "Created, not accepted",
            "title": "Title",
            "text": "Text",
            "created": "2020-07-21",
            "is_checked": true
        }

## Delivery List Filter [/api/delivery-filters/?service_type=Package+delivery&status=Created%2C+not+accepted&created=2020-07-21]

### Delivery List Filter [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "requester": {
                "first_name": "Aleksei",
                "last_name": "Support",
                "username": "Alex",
                "email": "kingdoom_98@mail.ru",
                "birthday": "2020-07-21",
                "age": 0,
                "gender": "Male",
                "phone": "0559129557",
                "address": "Address",
                "zip_code": "720010",
                "country": "Kyrgyzstan",
                "city": "Бишкек",
                "state": "Chui",
                "points": 20,
                "rating_count": 0,
                "avg_rating": 0,
                "avg_rating_last_ten": 0,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiZXhwIjoxNjAwNjcxNjg2fQ.Hrv_sRWj2R8Vg0C8NsCjo1YesWITZQC_gL79Ju4NVS4"
            },
            "provider": null,
            "service_type": "Package delivery",
            "start_location": "Start",
            "end_location": "End",
            "deadline": "2020-07-21T12:21:46Z",
            "status": "Created, not accepted",
            "title": "Title",
            "text": "Text",
            "created": "2020-07-21",
            "is_checked": true
        }

## Hosting List Filter [/api/hosting-filters/?service_type=Hosting&status=Created%2C+not+accepted&created=2020-07-21]

### Hosting List Filter [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "requester": {
                "first_name": "Alex",
                "last_name": "Chirkov",
                "username": "Scareface",
                "email": "admin@mail.ru",
                "birthday": "2020-07-21",
                "age": 0,
                "gender": "Male",
                "phone": "+996 559 129 557",
                "address": "Address",
                "zip_code": "720010",
                "country": "Kyrgyzstan",
                "city": "Test City",
                "state": "Chui",
                "points": 40,
                "rating_count": 2,
                "avg_rating": 4.0,
                "avg_rating_last_ten": 4.0,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAwNjcyMDI1fQ._R5cny-gXfqAIMjIrghgc0LL9Ce5iF--J7W7sOTMeVU"
            },
            "provider": null,
            "service_type": "Hosting",
            "title": "Title",
            "text": "Text",
            "date": "2020-07-21",
            "preferences": "Private bedroom",
            "status": "Created, not accepted",
            "created": "2020-07-21",
            "is_checked": true
        }

## Support List Filter [/api/support-filters/?name=Aleksei&date=2020-07-21]

### Support List Filter [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Aleksei",
            "email": "kingdoom_98@mail.ru",
            "title": "Title",
            "text": "Text",
            "date": "2020-07-21"
        }

## Request Service [/api/request-delivery/]

### Requset Service [GET]

+ Response 200 (application/json)

        <!--/api/request-delivery/-->
        <!--/api/request-hosting/-->
        <!--/api/request-pickup/-->
        {
            "id": 1,
            "service": {
                "id": 1,
                "requester": {
                    "first_name": "",
                    "last_name": "",
                    "username": "Admin",
                    "email": "tektonik_boy98@mail.ru",
                    "birthday": null,
                    "age": 0,
                    "gender": "",
                    "phone": null,
                    "address": null,
                    "zip_code": null,
                    "country": null,
                    "city": null,
                    "state": null,
                    "points": 0,
                    "rating_count": 0,
                    "avg_rating": 0,
                    "avg_rating_last_ten": 0,
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAxOTA0MzU1fQ.PxvBg4qUp07JrKWG2LykVClvDg05LaLn2gsohHrRpiE"
                },
                "provider": null,
                "pickup_location": "das",
                "drop_off_location": "asdasdas",
                "deadline": "2020-08-06",
                "status": "Created, not accepted",
                "title": "Title",
                "text": "asasssdf",
                "created": "2020-08-06",
                "is_checked": true
            },
            "requester": {
                "first_name": "",
                "last_name": "",
                "username": "Admin",
                "email": "tektonik_boy98@mail.ru",
                "birthday": null,
                "age": 0,
                "gender": "",
                "phone": null,
                "address": null,
                "zip_code": null,
                "country": null,
                "city": null,
                "state": null,
                "points": 0,
                "rating_count": 0,
                "avg_rating": 0,
                "avg_rating_last_ten": 0,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAxOTA0MzU1fQ.PxvBg4qUp07JrKWG2LykVClvDg05LaLn2gsohHrRpiE"
            },
            "status": "Pending",
            "accept": false
        }

### Request Service [POST]

+ Request (application/json)

        {
            "service": 1,
            "requester": 1,
            "status": "Pending",
            "accept": false
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/request-delivery/

    + Body

            <!--/api/request-delivery/-->
            <!--/api/request-hosting/-->
            <!--/api/request-pickup/-->
            {
                "id": 1,
                "service": {
                    "id": 1,
                    "requester": {
                        "first_name": "",
                        "last_name": "",
                        "username": "Admin",
                        "email": "tektonik_boy98@mail.ru",
                        "birthday": null,
                        "age": 0,
                        "gender": "",
                        "phone": null,
                        "address": null,
                        "zip_code": null,
                        "country": null,
                        "city": null,
                        "state": null,
                        "points": 0,
                        "rating_count": 0,
                        "avg_rating": 0,
                        "avg_rating_last_ten": 0,
                        "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAxOTA0MzU1fQ.PxvBg4qUp07JrKWG2LykVClvDg05LaLn2gsohHrRpiE"
                    },
                    "provider": null,
                    "pickup_location": "das",
                    "drop_off_location": "asdasdas",
                    "deadline": "2020-08-06",
                    "status": "Created, not accepted",
                    "title": "Title",
                    "text": "asasssdf",
                    "created": "2020-08-06",
                    "is_checked": true
                },
                "requester": {
                    "first_name": "",
                    "last_name": "",
                    "username": "Admin",
                    "email": "tektonik_boy98@mail.ru",
                    "birthday": null,
                    "age": 0,
                    "gender": "",
                    "phone": null,
                    "address": null,
                    "zip_code": null,
                    "country": null,
                    "city": null,
                    "state": null,
                    "points": 0,
                    "rating_count": 0,
                    "avg_rating": 0,
                    "avg_rating_last_ten": 0,
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAxOTA0MzU1fQ.PxvBg4qUp07JrKWG2LykVClvDg05LaLn2gsohHrRpiE"
                },
                "status": "Pending",
                "accept": false
            }

## Provide Delivery [/api/provide-delivery/]

### Provide Delivery List [GET]

+ Response 200 (application/json)

        {
            "id": 3,
            "requester": null,
            "provider": {
                "id": 1,
                "first_name": "",
                "last_name": "",
                "username": "admin",
                "email": "admin@mail.ru",
                "birthday": null,
                "age": 0,
                "gender": "",
                "phone": null,
                "address": null,
                "zip_code": null,
                "country": null,
                "city": null,
                "state": null,
                "points": 20,
                "rating_count": 0,
                "avg_rating": 0,
                "avg_rating_last_ten": 0,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAxOTA1NjI2fQ.bw5G6pYKTPwc1RvJOP8sy7OxPGllsPY9mZS1Kzno0K8"
            },
            "departure_location": "Kyrgyzstan",
            "departure_date": "2020-08-06",
            "arrival_location": "Location",
            "arrival_date": "2020-06-18T12:07:46Z", 
            "title": "Title",
            "hosting_type": "Private bedroom",
            "status": "Created, not accepted",
            "created": "2020-08-06",
            "is_checked": true
        }

### Create Provide Delivery [POST]

+ Request (application/json)

        {
            "requester": null,
            "provider": 1,
            "departure_location": "Kyrgyzstan",
            "departure_date": "2020-08-06",
            "arrival_location": "Location",
            "arrival_date": "2020-06-18T12:07:46Z", 
            "title": "Title",
            "hosting_type": "Private bedroom",
            "status": "Created, not accepted",
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/service/

    + Body

            {
                "id": 3,
                "requester": null,
                "provider": {
                    "id": 1,
                    "first_name": "",
                    "last_name": "",
                    "username": "admin",
                    "email": "admin@mail.ru",
                    "birthday": null,
                    "age": 0,
                    "gender": "",
                    "phone": null,
                    "address": null,
                    "zip_code": null,
                    "country": null,
                    "city": null,
                    "state": null,
                    "points": 20,
                    "rating_count": 0,
                    "avg_rating": 0,
                    "avg_rating_last_ten": 0,
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAxOTA1NjI2fQ.bw5G6pYKTPwc1RvJOP8sy7OxPGllsPY9mZS1Kzno0K8"
                },
                "departure_location": "Kyrgyzstan",
                "departure_date": "2020-08-06",
                "arrival_location": "Location",
                "arrival_date": "2020-06-18T12:07:46Z", 
                "title": "Title",
                "hosting_type": "Private bedroom",
                "status": "Created, not accepted",
                "created": "2020-08-06",
                "is_checked": true
            }

## Provide Pick Up [/api/provide-pickup/]

### Provide Pick Up List [GET]

+ Response 200 (application/json)

        {
            "id": 3,
            "requester": null,
            "provider": {
                "id": 1,
                "first_name": "",
                "last_name": "",
                "username": "admin",
                "email": "admin@mail.ru",
                "birthday": null,
                "age": 0,
                "gender": "",
                "phone": null,
                "address": null,
                "zip_code": null,
                "country": null,
                "city": null,
                "state": null,
                "points": 20,
                "rating_count": 0,
                "avg_rating": 0,
                "avg_rating_last_ten": 0,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAxOTA1NjI2fQ.bw5G6pYKTPwc1RvJOP8sy7OxPGllsPY9mZS1Kzno0K8"
            },
            "pickup_location": "Kyrgyzstan",
            "pickup_date": "2020-08-06",
            "title": "Title",
            "text": "Text",
            "status": "Created, not accepted",
            "created": "2020-08-06",
            "is_checked": true
        }

### Create Provide Pick Up [POST]

+ Request (application/json)

        {
            "requester": null,
            "provider": 1,
            "pickup_location": "Kyrgyzstan",
            "pickup_date": "2020-08-06",
            "title": "Title",
            "text": "Text",
            "status": "Created, not accepted",
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/service/

    + Body

            {
                "id": 3,
                "requester": null,
                "provider": {
                    "id": 1,
                    "first_name": "",
                    "last_name": "",
                    "username": "admin",
                    "email": "admin@mail.ru",
                    "birthday": null,
                    "age": 0,
                    "gender": "",
                    "phone": null,
                    "address": null,
                    "zip_code": null,
                    "country": null,
                    "city": null,
                    "state": null,
                    "points": 20,
                    "rating_count": 0,
                    "avg_rating": 0,
                    "avg_rating_last_ten": 0,
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAxOTA1NjI2fQ.bw5G6pYKTPwc1RvJOP8sy7OxPGllsPY9mZS1Kzno0K8"
                },
                "location": "Kyrgyzstan",
                "hosting_date": "2020-08-06",
                "title": "Title",
                "text": "Text",
                "status": "Created, not accepted",
                "created": "2020-08-06",
                "is_checked": true
            }

## Provide Hosting [/api/provide-hosting/]

### Provide Hosting List [GET]

+ Response 200 (application/json)

        {
            "id": 3,
            "requester": null,
            "provider": {
                "id": 1,
                "first_name": "",
                "last_name": "",
                "username": "admin",
                "email": "admin@mail.ru",
                "birthday": null,
                "age": 0,
                "gender": "",
                "phone": null,
                "address": null,
                "zip_code": null,
                "country": null,
                "city": null,
                "state": null,
                "points": 20,
                "rating_count": 0,
                "avg_rating": 0,
                "avg_rating_last_ten": 0,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAxOTA1NjI2fQ.bw5G6pYKTPwc1RvJOP8sy7OxPGllsPY9mZS1Kzno0K8"
            },
            "location": "Location",
            "hosting_date": "2020-06-18",
            "title": "Title",
            "text": "Text",
            "hosting_type": "Private bedroom",
            "status": "Created, not accepted",
            "created": "2020-08-06",
            "is_checked": true
        }

### Create Provide Hosting [POST]

+ Request (application/json)

        {
            "requester": null,
            "provider": 1,
            "location": "Kyrgyzstan",
            "hosting_date": "2020-08-06",
            "title": "Title",
            "text": "Text",
            "hosting_type": "Private bedroom",
            "status": "Created, not accepted",
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/service/

    + Body

            {
                "id": 3,
                "requester": null,
                "provider": {
                    "id": 1,
                    "first_name": "",
                    "last_name": "",
                    "username": "admin",
                    "email": "admin@mail.ru",
                    "birthday": null,
                    "age": 0,
                    "gender": "",
                    "phone": null,
                    "address": null,
                    "zip_code": null,
                    "country": null,
                    "city": null,
                    "state": null,
                    "points": 20,
                    "rating_count": 0,
                    "avg_rating": 0,
                    "avg_rating_last_ten": 0,
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAxOTA1NjI2fQ.bw5G6pYKTPwc1RvJOP8sy7OxPGllsPY9mZS1Kzno0K8"
                },
                "location": "Location",
                "hosting_date": "2020-06-18",
                "title": "Title",
                "text": "Text",
                "hosting_type": "Private bedroom",
                "status": "Created, not accepted",
                "created": "2020-08-06",
                "is_checked": true
            }

## Request Service Provide [/api/request-provide-delivery/]

### Requset Service Provide List [GET]

+ Response 200 (application/json)

        <!--/api/request-delivery/-->
        <!--/api/request-hosting/-->
        <!--/api/request-pickup/-->
        {
            "id": 1,
            "service": {
                "id": 1,
                "requester": {
                    "first_name": "",
                    "last_name": "",
                    "username": "Admin",
                    "email": "tektonik_boy98@mail.ru",
                    "birthday": null,
                    "age": 0,
                    "gender": "",
                    "phone": null,
                    "address": null,
                    "zip_code": null,
                    "country": null,
                    "city": null,
                    "state": null,
                    "points": 0,
                    "rating_count": 0,
                    "avg_rating": 0,
                    "avg_rating_last_ten": 0,
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAxOTA0MzU1fQ.PxvBg4qUp07JrKWG2LykVClvDg05LaLn2gsohHrRpiE"
                },
                "provider": null,
                "pickup_location": "das",
                "drop_off_location": "asdasdas",
                "deadline": "2020-08-06",
                "status": "Created, not accepted",
                "title": "Title",
                "text": "asasssdf",
                "created": "2020-08-06",
                "is_checked": true
            },
            "requester": {
                "first_name": "",
                "last_name": "",
                "username": "Admin",
                "email": "tektonik_boy98@mail.ru",
                "birthday": null,
                "age": 0,
                "gender": "",
                "phone": null,
                "address": null,
                "zip_code": null,
                "country": null,
                "city": null,
                "state": null,
                "points": 0,
                "rating_count": 0,
                "avg_rating": 0,
                "avg_rating_last_ten": 0,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAxOTA0MzU1fQ.PxvBg4qUp07JrKWG2LykVClvDg05LaLn2gsohHrRpiE"
            },
            "status": "Pending",
            "accept": false
        }

### Request Service [POST]

+ Request (application/json)

        {
            "service": 1,
            "requester": 1,
            "status": "Pending",
            "accept": false
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/request-provide-delivery/

    + Body

            <!--/api/request-provide-delivery/-->
            <!--/api/request-provide-hosting/-->
            <!--/api/request-provide-pickup/-->
            {
                "id": 1,
                "service": {
                    "id": 1,
                    "requester": {
                        "first_name": "",
                        "last_name": "",
                        "username": "Admin",
                        "email": "tektonik_boy98@mail.ru",
                        "birthday": null,
                        "age": 0,
                        "gender": "",
                        "phone": null,
                        "address": null,
                        "zip_code": null,
                        "country": null,
                        "city": null,
                        "state": null,
                        "points": 0,
                        "rating_count": 0,
                        "avg_rating": 0,
                        "avg_rating_last_ten": 0,
                        "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAxOTA0MzU1fQ.PxvBg4qUp07JrKWG2LykVClvDg05LaLn2gsohHrRpiE"
                    },
                    "provider": null,
                    "pickup_location": "das",
                    "drop_off_location": "asdasdas",
                    "deadline": "2020-08-06",
                    "status": "Created, not accepted",
                    "title": "Title",
                    "text": "asasssdf",
                    "created": "2020-08-06",
                    "is_checked": true
                },
                "requester": {
                    "first_name": "",
                    "last_name": "",
                    "username": "Admin",
                    "email": "tektonik_boy98@mail.ru",
                    "birthday": null,
                    "age": 0,
                    "gender": "",
                    "phone": null,
                    "address": null,
                    "zip_code": null,
                    "country": null,
                    "city": null,
                    "state": null,
                    "points": 0,
                    "rating_count": 0,
                    "avg_rating": 0,
                    "avg_rating_last_ten": 0,
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjAxOTA0MzU1fQ.PxvBg4qUp07JrKWG2LykVClvDg05LaLn2gsohHrRpiE"
                },
                "status": "Pending",
                "accept": false
            }