# Generated by Django 3.0.7 on 2020-06-14 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Package delivery', 'Package delivery'), ('Airport pick up/drop off', 'Airport pick up/drop off'), ('Hosting', 'Hosting')], max_length=32)),
                ('start_location', models.CharField(max_length=128)),
                ('end_location', models.CharField(max_length=128)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('Created, not accepted', 'Created, not accepted'), ('Accepted/in process', 'Accepted/in process'), ('Successfully done', 'Successfully done'), ('Not confirmed', 'Not confirmed'), ('Canceled', 'Canceled')], max_length=64)),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField(max_length=512)),
                ('image', models.ImageField(upload_to='')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
    ]
