# Generated by Django 3.0.7 on 2020-08-03 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpickup',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestpickup',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.PickUp'),
        ),
        migrations.AddField(
            model_name='requesthosting',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requesthosting',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Hosting'),
        ),
        migrations.AddField(
            model_name='requestdelivery',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestdelivery',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Delivery'),
        ),
        migrations.AddField(
            model_name='providepickup',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_prov', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providepickup',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_req', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providehosting',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosting_prov', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providehosting',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosting_req', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providedelivery',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_prov', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providedelivery',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_req', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickup',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickup',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hosting',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosting_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hosting',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosting_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
