# Generated by Django 3.0.7 on 2020-06-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200616_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='requester',
        ),
        migrations.DeleteModel(
            name='AvgRating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
