# Generated by Django 3.0.7 on 2020-08-15 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_auto_20200815_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provideservice',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='provideservice',
            name='arrival_location',
        ),
        migrations.RemoveField(
            model_name='provideservice',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='provideservice',
            name='departure_location',
        ),
        migrations.AddField(
            model_name='provideservice',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provideservice',
            name='drop_off_location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='provideservice',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='provideservice',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='provideservice',
            name='preferences',
            field=models.CharField(blank=True, choices=[('Private bedroom', 'Private bedroom'), ('Living room', 'Living room'), ('Common space', 'Common space')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='provideservice',
            name='provider_from',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='provideservice',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_service_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provideservice',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Delivery', 'Delivery'), ('Pick Up', 'Pick Up'), ('Hosting', 'Hosting')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='provideservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provide_service_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestprovideservice',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestprovideservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
    ]
