# Generated by Django 3.0.7 on 2020-06-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200618_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
