# Generated by Django 3.0.7 on 2020-06-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200618_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='service_type',
            field=models.CharField(choices=[('Hosting', 'Hosting')], default='Hosting', max_length=32),
        ),
    ]
