# Generated by Django 2.2 on 2020-09-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200910_1155'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='requestservice',
            constraint=models.UniqueConstraint(fields=('requester', 'service'), name='unique_request_service'),
        ),
    ]
