# Generated by Django 3.0.7 on 2020-08-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200806_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='location',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
