# Generated by Django 3.0.7 on 2020-08-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_hosting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='requester_from',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
