# Generated by Django 3.0.7 on 2020-06-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200616_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='status',
            field=models.CharField(choices=[('Created, not accepted', 'Created, not accepted'), ('Accepted/in process', 'Accepted/in process'), ('Successfully done', 'Successfully done'), ('Not confirmed', 'Not confirmed'), ('Canceled', 'Canceled')], default='Created, not accepted', max_length=64),
        ),
    ]
