# Generated by Django 3.0.7 on 2020-08-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200815_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideservice',
            name='status',
            field=models.CharField(blank=True, choices=[('Created, not accepted', 'Created, not accepted'), ('Accepted/in process', 'Accepted/in process'), ('Successfully done', 'Successfully done'), ('Not confirmed', 'Not confirmed'), ('Canceled', 'Canceled')], default='Created, not accepted', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='provideservice',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
