# Generated by Django 3.0.7 on 2020-08-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_hosting_requester_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='text',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='text',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='text',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='providedelivery',
            name='text',
            field=models.TextField(blank=True, max_length=640, null=True),
        ),
        migrations.AlterField(
            model_name='providehosting',
            name='text',
            field=models.CharField(blank=True, max_length=640, null=True),
        ),
        migrations.AlterField(
            model_name='providepickup',
            name='text',
            field=models.TextField(blank=True, max_length=640, null=True),
        ),
    ]
