# Generated by Django 3.0.7 on 2020-08-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200815_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideservice',
            name='status',
            field=models.CharField(blank=True, choices=[('Created, not accepted', 'Created, not accepted'), ('Accepted/in process', 'Accepted/in process'), ('Successfully done', 'Successfully done'), ('Not confirmed', 'Not confirmed'), ('Expired', 'Expired'), ('Canceled', 'Canceled')], default='Created, not accepted', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='requestprovideservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ProvideService'),
        ),
    ]
