# Generated by Django 3.0.7 on 2020-08-04 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200803_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='deliveries')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.Delivery')),
            ],
        ),
    ]
