# Generated by Django 3.0.7 on 2020-08-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200815_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideservice',
            name='arrive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
