# Generated by Django 3.0.7 on 2020-08-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_deliveryimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='image',
        ),
    ]
