# Generated by Django 3.0.7 on 2020-08-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_delivery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deliveries'),
        ),
    ]
