# Generated by Django 3.0.7 on 2020-08-04 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_delivery_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryImages',
            new_name='DeliveryImage',
        ),
        migrations.CreateModel(
            name='PickUpImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pick_ups')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.PickUp')),
            ],
        ),
        migrations.CreateModel(
            name='HostingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pick_ups')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.Hosting')),
            ],
        ),
    ]
