# Generated by Django 3.0.7 on 2020-08-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20200813_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryimage',
            name='image',
            field=models.ImageField(upload_to='deliveries'),
        ),
    ]
