# Generated by Django 3.0.7 on 2020-08-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20200804_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='name',
        ),
    ]
